images:
  repository: 930385231819.dkr.ecr.eu-north-1.amazonaws.com/microservices-demo
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0

serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false

networkPolicies:
  create: false

sidecars:
  create: false

authorizationPolicies:
  create: false

securityContext:
  enable: true

opentelemetryCollector:
create: false
name: opentelemetrycollector
# Specifies the project id for the otel collector. If set as "PROJECT_ID" (default value), an initContainer will automatically retrieve the project id value from the metadata server.
projectId: "PROJECT_ID"

googleCloudOperations:
profiler: false
tracing: false
metrics: false

seccompProfile:
enable: false
type: RuntimeDefault

cartService:
  create: true
  name: cartservice
  tag: <+artifacts.primary.tag>
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

cartDatabase:
  # Specifies the type of the cartservice's database, could be either redis or spanner.
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    # Uses the public redis image from Docker Hub, otherwise will use the images.repository.
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
    name: exernal-redis-tls-origination
    endpointAddress: ""
    endpointPort: ""
    certificate: ""
