pipeline:
  name: cartservice
  identifier: cartservice
  tags: {}
  template:
    templateRef: Golang_CI_pipeline
    versionLabel: "1"
    gitBranch: main
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      variables:
        - name: language
          type: String
          value: <+input>.selectOneFrom(golang,java,dotnet,python,javascript)
        - name: service_name
          type: String
          value: <+input>
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
