pipeline:
  name: Non Prod Deploy
  identifier: Deploy_Single_Service
  tags: {}
  template:
    templateRef: Non_Prod_Single_Service_Deployment
    versionLabel: "1"
    gitBranch: main
    templateInputs:
      stages:
        - stage:
            identifier: Deploy
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
