pipeline:
  name: productcatalogservice-ci
  identifier: productcatalogservice
  tags: {}
  template:
    templateRef: Golang_CI_pipeline
    versionLabel: "1"
    gitBranch: main
    templateInputs:
      stages:
        - parallel:
            - stage:
                identifier: Java_Test
                template:
                  templateInputs:
                    type: CI
                    variables:
                      - name: skipTests
                        type: String
                        value: <+input>.default(false).selectOneFrom(false,true)
        - stage:
            identifier: Build_Scan_Push
            template:
              templateInputs:
                type: CI
                spec:
                  execution:
                    steps:
                      - stepGroup:
                          identifier: BuildScanPush
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: Ingest_Trivy_Image_Scan
                                    template:
                                      templateInputs:
                                        type: CustomIngest
                                        spec:
                                          target:
                                            type: container
                                            variant: <+input>
      properties:
        ci:
          codebase:
            build: <+input>
      variables:
        - name: language
          type: String
          value: <+input>.selectOneFrom(golang,java,dotnet,python,javascript)
        - name: service_name
          type: String
          value: <+input>
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
