pipeline:
  name: Prod Deployment
  identifier: Prod_Deployment
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
  tags: {}
  stages:
    - stage:
        name: depl
        identifier: depl
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: adservice
            serviceInputs:
              serviceDefinition:
                type: NativeHelm
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: DEV
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devcluster
                inputs:
                  identifier: devcluster
                  type: KubernetesDirect
                  spec:
                    namespace: default
          execution:
            steps:
              - step:
                  type: HelmDeploy
                  name: HelmDeploy_1
                  identifier: HelmDeploy_1
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: HelmBlueGreenSwapStep
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  delegateSelectors:
    - dev
