pipeline:
  name: productcatalogservice
  identifier: productcatalogservice
  tags: {}
  template:
    templateRef: Golang_CI_pipeline
    versionLabel: "1"
    gitBranch: main
    templateInputs:
      stages:
        - stage:
            identifier: Build_Scan_Push
            template:
              templateInputs:
                type: CI
                spec:
                  execution:
                    steps:
                      - stepGroup:
                          identifier: BuildScanPush
                          template:
                            templateInputs:
                              variables:
                                - name: docker_tag
                                  type: String
                                  value: <+input>
      properties:
        ci:
          codebase:
            build: <+input>
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
