pipeline:
  name: productcatalogservice-promotion
  identifier: productcatalogservicepromotion
  tags: {}
  template:
    templateRef: Image_Promotion
    versionLabel: "1"
    gitBranch: main
    templateInputs:
      variables:
        - name: service_name
          type: String
          value: <+input>
        - name: promotion_type
          type: String
          value: <+input>.selectOneFrom(PR,Tag)
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
