pipeline:
  name: productcatalogservice
  identifier: productcatalogservice
  tags: {}
  template:
    templateRef: Golang_CI_pipeline
    versionLabel: "1"
    gitBranch: main
    templateInputs:
      stages:
        - stage:
            identifier: Security_Scans
            template:
              templateInputs:
                type: SecurityTests
                spec:
                  execution:
                    steps:
                      - parallel:
                          - stepGroup:
                              identifier: Scan_and_Ingest_Secrets
                              template:
                                templateInputs:
                                  steps:
                                    - step:
                                        identifier: GitLeaks_ingest
                                        template:
                                          templateInputs:
                                            type: CustomIngest
                                            spec:
                                              target:
                                                type: repository
                                                variant: <+input>
                          - stepGroup:
                              identifier: Semgrep
                              template:
                                templateInputs:
                                  steps:
                                    - step:
                                        identifier: Semgrep_Ingest
                                        template:
                                          templateInputs:
                                            type: CustomIngest
                                            spec:
                                              target:
                                                type: repository
                                                variant: <+input>
        - stage:
            identifier: Build_Scan_Push
            template:
              templateInputs:
                type: CI
                spec:
                  infrastructure:
                    type: KubernetesDirect
                    spec:
                      serviceAccountName: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: BuildScanPush
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: Ingest_Trivy_Image_Scan
                                    template:
                                      templateInputs:
                                        type: CustomIngest
                                        spec:
                                          target:
                                            type: container
                                            variant: <+input>
                              variables:
                                - name: docker_tag
                                  type: String
                                  value: <+input>
                                - name: ecr_repo_name
                                  type: String
                                  value: <+input>
      properties:
        ci:
          codebase:
            build: <+input>
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
