pipeline:
  name: Prod Deployment
  identifier: Prod_Deployment
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: microservicesdemo
            disableArtifactValidation: true
          environment:
            environmentRef: DEV
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devcluster
                inputs:
                  identifier: devcluster
                  type: KubernetesDirect
                  spec:
                    namespace: default
          execution:
            steps:
              - step:
                  type: HelmCanaryDeploy
                  name: HelmCanaryDeploy_1
                  identifier: HelmCanaryDeploy_1
                  spec:
                    ignoreReleaseHistFailStatus: false
                    skipSteadyStateCheck: false
                    instanceSelection:
                      type: Count
                      spec:
                        count: 1
                  timeout: 10m
              - step:
                  type: HelmCanaryDelete
                  name: HelmCanaryDelete_1
                  identifier: HelmCanaryDelete_1
                  spec: {}
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: HelmCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - dev
  delegateSelectors:
    - dev
