images:
  repository: 930385231819.dkr.ecr.eu-north-1.amazonaws.com/microservices-demo
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0

serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false

networkPolicies:
  create: false

sidecars:
  create: false

authorizationPolicies:
  create: false

securityContext:
  enable: true

opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  # Specifies the project id for the otel collector. If set as "PROJECT_ID" (default value), an initContainer will automatically retrieve the project id value from the metadata server.
  projectId: "PROJECT_ID"

googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false

seccompProfile:
  enable: false
  type: RuntimeDefault

frontend:
  create: true
  name: frontend
  tag: <+artifacts.primary.tag>
  externalService: true
  cymbalBranding: false
  # One of: local, gcp, aws, azure, onprem, alibaba. When not set, defaults to "local" unless running in GKE, otherwise auto-sets to gcp.
  platform: local
  singleSharedSession: false
  virtualService:
    create: false
    hosts:
      - "*"
    gateway:
      name: asm-ingressgateway
      namespace: asm-ingress
      labelKey: asm
      labelValue: ingressgateway
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
